run:
	docker run -it --rm --name import-user-kata -v .:/usr/src/myapp -w /usr/src/myapp composer:latest php run.php

bash:
	docker run -it --rm --name import-user-kata -v .:/usr/src/myapp -w /usr/src/myapp composer:latest /bin/sh